[package]
name = "twig"
version = "2.0.0-alpha01"
authors = ["IDivisionTeam", "idivision.developer@gmail.com"]
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["cargo", "color", "derive"] }
serde = { version = "1.0.219", features = ["derive", "alloc"] }
serde_json = "1.0.141"
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
base64 = "0.22.1"
anyhow = "1.0.100"
figment = { version = "0.10.19", features = ["toml", "test"] }
toml = "0.9.8"
thiserror = "2.0.17"
regex = "1.12.2"
unicode-normalization = "0.1.25"
log = "0.4.29"
env_logger = "0.11.8"

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3.27.0"
