[package]
name = "twig"
version = "2.0.0-alpha01"
authors = ["IDivisionTeam", "idivision.developer@gmail.com"]
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["cargo", "color"] }