name: twig

on:
  push:
    branches: [ "main-rs" ]
  pull_request:
    branches: [ "main-rs" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && !contains(github.event.head_commit.message, 'docs:') }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Install Dependency Checker
        run: cargo install cargo-audit

      - name: Analyze Dependencies
        run: cargo audit

      - name: Build
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy --verbose -- -D warnings

      - name: Test
        run: cargo test --verbose
